### ISSUE TITLE
MDTest hard on Lustre

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/io500#15]
This issue is to document and discuss the known problem of running MDtest hard on Lustre which may abort due to a "No space left on device" error. The reason is that by default, with LDiskFS:
"We use the ext3 hashed directory code, which has a theoretical limit of about 15 million files per directory".
With a deployed DNE2 or a specific mount option, this limit can be avoided.

**Comment by adilger** [comment]
There are two mechanisms to increase the ~15M files-per-directory limit, both of which are orthogonal and can be used together:
- in the `io500.sh` script's `setup_directories` function, use "`lfs setdirstripe -D -c -1 $io500_workdir`" to set the default directory striping for all subdirectories created therein.  This will cause all subdirectories created under that directory to be striped over all available MDTs, which is appropriate for very large directories such as `mdtest-easy` and `mdtest-hard` and does not hurt the `ior-easy` or `ior-hard` results.
- enable the `large_dir` feature for all MDTs (this must be done by the administrators via `tune2fs -O large_dir /dev/<mdtdev>` for each MDT).  This requires at least `[e2fsprogs-1.45.6.wc2](https://downloads.whamcloud.com/public/e2fsprogs/)` to understand this feature.

**Comment by adilger** [comment]
Of course, it is also possible that the MDT(s) may actually run out of space, if the creation rate is high, and there is not enough free inodes on the MDTs, or if Data-on-MDT is not used for the small files and there are not enough inodes on the OSTs.  The free and used inodes can be checked by running "`lfs df -i`" on any client.

**Comment by wszoecs** [comment]
The issue with 'mdt-hard' (shared dir file-create) - is abs. not in 'large_dir' - but the way how ldiskfs does directories:
It uses HASHED buckets - to place the files.
And due to the hilarious naming of mdtest - your files all end in 1-2 maybe 4 buckets - and fills thos up.
So - even if you still have several millions of entries available - you're running out of available entries in a few hash-buckets.
my experiments say - per MDS - at around 8 mill - you're DONE - and always/reliably run out of space in this test.
